# 11 i:- Program to demonstrate file handling, 
 # To write data in to the file 
    use strict; 
    use warnings; 
    open(my $fh, '>', 'report.txt'); 
    print $fh "My first report generated by perl\n"; 
    close $fh; 
    print "done\n";

